apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pgrok.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "update", "patch", "delete", "get", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "update", "patch", "delete", "get", "list"]