apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgrok.fullname" . }}
type: Opaque
data:
  ssh_host_ecdsa_key: {{ .Values.pgrok.hostKeys.ecdsa | required "ecdsa is required!" | b64enc }}
  ssh_host_ed25519_key: {{ .Values.pgrok.hostKeys.ed25519 | required "ed25519 is required!" | b64enc }}
  ssh_host_rsa_key: {{ .Values.pgrok.hostKeys.rsa | required "rsa is required!" | b64enc }}