apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pgrok.serviceAccountName" . }}
  labels:
    {{- include "pgrok.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
