apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgrok.fullname" . }}
  labels:
    {{- include "pgrok.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "pgrok.selectorLabels" . | nindent 4 }}
