name: Docker Image CI

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Login to GitHub Container Registry
      uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        tag="${GITHUB_REF##*/}"
        if [ "$tag" = "main" ]
        then
          tag='latest'
        fi
        repo_name="ghcr.io/pschichtel/pgrok"
        image_name="$repo_name:$tag"
        podman build -t "$image_name" .
        podman push "$image_name"

