name: Docker Image CI

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - name: Login to GitHub Container Registry
      uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        tag="${GITHUB_REF##*/}"
        if [ "$tag" = "main" ]
        then
          tag='latest'
        fi
        repo_name="ghcr.io/pschichtel/pgrok"
        image_name="$repo_name:$tag"
        podman build -t "$image_name" .
        podman push "$image_name"

