name: Docker Image CI

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - name: Login to GitHub Container Registry
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        tag="${GITHUB_REF##*/}"
        if [ "$tag" = "main" ]
        then
          tag='latest'
        fi
        repo_name="ghcr.io/pschichtel/pgrok"
        image_name="$repo_name:$tag"
        podman build -t "$image_name" .
        podman push "$image_name"

