name: Docker Image CI

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        tag="${GITHUB_REF##*/}"
        if [ "$tag" = "main" ]
        then
          tag='latest'
        fi
        repo_name="ghcr.io/pschichtel/pgrok"
        image_name="$repo_name:$tag"
        podman build -t "$image_name" .
        podman push "$image_name"

